version: '3.2'

services:

  fpm:
    build: docker/fpm
    environment:
      APP_ENV: dev
      APP_SECRET: change_me
      ALLOWED_ORIGIN: localhost
      MESSENGER_TRANSPORT_DSN: "redis://redis:6379/php8-stack"
      MONGODB_DSN: "mongodb://mongo:27017"
      MONGODB_DATABASE: "php8-stack"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
      - mongo
    volumes:
      - '.:/var/www/html'

  nginx:
    depends_on:
      - fpm
    image: nginx:alpine
    links:
      - fpm
    ports:
      - 8080:80
    volumes:
      - './public:/var/www/html/public:cached'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'

  cli:
    build: docker/cli
    environment:
      APP_ENV: dev
      MONGODB_DSN: "mongodb://mongo:27017"
      MONGODB_DATABASE: "php8-stack"
    links:
      - mongo
    volumes:
      - .:/srv/php/app

  mongo:
    image: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_DATABASE: php8-stack

  redis:
    image: redis
    hostname: redis
